### PR TITLE
Ⓔ

### PR DESCRIPTION
**Pull request by noamhacker**
added an important section in the code of conduct

### CODE REVIEW

**Comment by SamWheating** [comment]
eeeeeeeeeeeeeeeeeeeeeeee

**Comment by jackharrhy** [comment]
_important section_

**Comment by hugginsio** [comment]
I second this notion.

**Comment by lugray** [comment]
This repo is getting lots of attention from a wide variety of people.  Keep the code of conduct serious is probably a good idea.

**Review by alisherry — APPROVED** [review]
LGTM

**Comment by noamhacker** [comment]
```
eeeeeeeeeee
:(
```

**Pull request closed without merging**
