### PR TITLE
Put it in a circle

### PR DESCRIPTION
**Pull request by ngscheurich**
e → ⃝

### CODE REVIEW

**Comment by alexandrecruz** [comment]
ee ee e eeee #78 eeee e e eee ee?!!

*eee e e*: eee eeeee eee!

@ilianaw eee ee?

**Review by riptidewave93 — COMMENTED** [review]
eee eeeee ee eeeeeee?

**Comment by g33kidd** [comment]
e?

**Comment by jomo** [comment]
>e → ⃝

e⃝

**Review by brendonpagano — COMMENTED** [review]
eeeeeeeeeeeee

**Comment by HoyerHub** [comment]
Ⓔ

**Pull request merged**
