### PR TITLE
Create e.swift

### PR DESCRIPTION
**Pull request by tommy60703**

### CODE REVIEW

**Comment by ramesaliyev** [comment]
ee?

**Comment by hiking93** [comment]
Eeee eee!

**Review by kiritokatklian — APPROVED** [review]

**Review by kiritokatklian — COMMENTED** [review]
eeeeeeeeeee

**Comment by LiaoJimmy** [comment]
Please refer to [e.c](https://github.com/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/blob/eeeeeeeeeeeeeeeeeeeeeeee/e.c), [e.go](https://github.com/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/blob/eeeeeeeeeeeeeeeeeeeeeeee/e.go) or [e.java](https://github.com/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/blob/eeeeeeeeeeeeeeeeeeeeeeee/e.java).
You miss a `while` loop.

```swift
while true {
  print("e")
}
```

**Comment by LinuxMercedes** [comment]
eeee ee!!!

**Pull request merged**
