### PR TITLE
Add e.properties

### PR DESCRIPTION
**Pull request by TwiN**
- eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
- eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
- eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
- eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

### CODE REVIEW

**Comment by curi0us** [comment]
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by TwiN** [comment]
eeeeeeeeeeeeeeeeeeeeeeeeeeeee?

**Comment by xseano** [comment]
eeeeeeeeeeeee!

**Comment by TwiN** [comment]
eeeeee?!

**Comment by LinuxMercedes** [comment]
eee eee eee eee eeee ee eeee? `e.properies` -> `e.properties` :heart:

**Comment by TwiN** [comment]
!!! eeeeee!! >.<

**Comment by TwiN** [comment]
@LinuxMercedes eeeee eee 👍

**Comment by LinuxMercedes** [comment]
e :heart:

**Pull request merged**
