### PR TITLE
Optimize e.go implementation

### PR DESCRIPTION
**Pull request by cristaloleg**
- Reduce binary size
- Reduce cognitive load

### CODE REVIEW

**Review by quasilyte — APPROVED** [review]

**Comment by quasilyte** [comment]
You could run linters just in case, to be sure that you've broken nothing.
I would suggest https://github.com/golangci/golangci-lint.

**Comment by cristaloleg** [comment]
No warning on the default list of checkers.

**Comment by iliana** [comment]
Here at e98e we are all for reduction of cognitive load

**Comment by ghost** [comment]
I have found a bug, seems like this branch does something cheaty and somehow overlooks stdin and prints the `e` to the stderr. i need more information on this and possibly some team dedicated to fixing this bug.

**Comment by cristaloleg** [comment]
OMG

**Pull request merged**
