### PR TITLE
e.py3

### PR DESCRIPTION
**Pull request by yk-sgr**

### CODE REVIEW

**Comment by iliana** [comment]
https://github.com/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/blob/eeeeeeeeeeeeeeeeeeeeeeee/e.py is already Python 3 compatible, isn't it?

**Comment by yk-sgr** [comment]
but it's just .py extension

**Comment by mzhang28** [comment]
Python 3 also uses `.py` extension.

**Comment by yk-sgr** [comment]
.php3 got also merged

**Comment by mzhang28** [comment]
Although I don't agree with having `.php3` extension merged, `.php3` is commonly used as an extension for PHP files, while `.py3` isn't used in favor of the generic `.py`.

**Pull request closed without merging**
