### PR TITLE
such applescript. many say. wow.

### PR DESCRIPTION
**Pull request by hbmartin**

### CODE REVIEW

**Comment by LinuxMercedes** [comment]
Eeee eeee! ee EE eE eeEE eeE!

**Comment by tieutantan** [comment]
Hi all, why this project is only "eeeeeeeeeeeeeeeeeeeeeee" hahaha, I don't understand.

**Comment by LinuxMercedes** [comment]
Eeeeeee eee eee!!

**Comment by hbmartin** [comment]
@tieutantan why is there something instead of nothing?

**Pull request merged**
